const mongoose = require('mongoose')
let OrderSchema = mongoose.Schema({
user:{
    type:mongoose.Schema.Types.ObjectId,
    ref:'User'
},
address:{
    type:mongoose.Schema.Types.ObjectId,
    ref:'Address'
},
products:[
    {
        product:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Products"
        },
        productName:{
            type:String,
            required:true
        },
        url:{
            type:String,
            required:true
        },
        qty:{
            type:Number,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
    }
],
total:{
    type:Number,
    required:true
},
payment:{
    type:Boolean,
    default:false
    },
    OrderId:{
        type:Number,
        default:()=>{
            return Math.floor(Math.random()*900000000300000000000) + 1000000000000000
        },
        createIndexes: { unique: true }
    }
})
module.exports=User=mongoose.model('Order',OrderSchema)